version: '3.1'

networks: 
  misp-backend:
    driver: bridge
    driver_opts:
     com.docker.network.bridge.name: "${BRIDGE_NAME}"
     com.docker.network.enable_ipv6: "false"
    ipam:
      config:
      - subnet: "${DOCKER_NETWORK}"

services:
  # ### MISP Database ###
  # # LINK: https://hub.docker.com/_/mariadb/
  # misp-db:
  #   # default-image-db=mariadb:10.3.10-bionic
  #   image: ${MISP_IMAGE_DB}
  #   container_name: misp-db
  #   restart: unless-stopped
  #   environment:
  #     # DB
  #     MYSQL_ROOT_PASSWORD: ${MISP_MYSQL_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${MISP_MYSQL_DATABASE}
  #     MYSQL_USER: ${MISP_MYSQL_USER}
  #     MYSQL_PASSWORD: ${MISP_MYSQL_PASSWORD}
  #   volumes:
  #   - misp-vol-db-data:/var/lib/mysql/"
  #   healthcheck:
  #     test: ["CMD-SHELL", "mysql -u $MYSQL_USER -p$MYSQL_PASSWORD -h misp-db --execute 'show databases;'"]
  #     interval: 1m
  #     timeout: 15s
  #     retries: 5
  #   networks:
  #     misp-backend:
  #       aliases:
  #       - misp-db 

  ### MISP Redis Server ###
  # LINK: https://docs.docker.com/samples/library/redis/
  # LINK: https://github.com/docker-library/docs/tree/master/redis
  misp-redis:
    # default-image-redis=dockerhub.dcso.de/misp-dockerized-redis:5-alpine3.9
    image: ${MISP_IMAGE_REDIS}
    restart: unless-stopped
    container_name: misp-redis
    command: ["redis-server", "--appendonly", "yes"] #For Data persistence
    healthcheck:
      test: ["CMD-SHELL", "[ $$(redis-cli ping) == PONG ] || exit 1"]
      interval: 1m30s
      timeout: 15s
      retries: 3
    volumes:
    - misp-vol-redis-data:/data/
    networks:
      misp-backend:
        aliases:
        - misp-redis
  
  ### MISP Modules ###
  misp-modules:
    # default-image-modules=dockerhub.dcso.de/misp-dockerized-misp-modules:latest
    image: ${MISP_IMAGE_MODULES}
    container_name: misp-modules
    restart: unless-stopped
    environment:
      # REDIS
      REDIS_BACKEND: ${MISP_REDIS_FQDN}
      REDIS_PORT: ${MISP_REDIS_PORT}
      REDIS_PW: ${MISP_REDIS_PW}
      REDIS_DATABASE: ${MISP_REDIS_DATABASE}
      # PROXY
      http_proxy: ${MISP_PROXY_HTTP}
      https_proxy: ${MISP_PROXY_HTTPS}
      no_proxy:  ${MISP_PROXY_NO}
    networks:
      misp-backend:
        aliases:
          - misp-modules


  ### MISP Apache Server ###    
  misp-server:
    # default-image-server=dockerhub.dcso.de/misp-dockerized-server:2.4.117-debian
    image: ${MISP_IMAGE_SERVER}
    container_name: misp-server
    restart: unless-stopped
    environment:
      # DB
      MYSQL_HOST: ${MISP_MYSQL_HOST}
      MYSQL_PORT: ${MISP_MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: ${MISP_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MISP_MYSQL_DATABASE}
      MYSQL_USER: ${MISP_MYSQL_USER}
      MYSQL_PASSWORD: ${MISP_MYSQL_PASSWORD}
      # REDIS
      REDIS_FQDN: ${MISP_REDIS_FQDN}
      REDIS_PORT: ${MISP_REDIS_PORT}
      REDIS_PW: ${MISP_REDIS_PW}
      REDIS_DATABASE: ${MISP_REDIS_DATABASE}
      # PROXY
      http_proxy: ${MISP_PROXY_HTTP}
      https_proxy: ${MISP_PROXY_HTTPS}
      no_proxy:  ${MISP_PROXY_NO}
      # POSTFIX
      SENDER_ADDRESS: ${MISP_POSTFIX_SENDER_ADDRESS}
      DOMAIN: ${MISP_POSTFIX_DOMAIN}
      HTTP_SERVERADMIN: ${MISP_HTTP_SERVERADMIN}
      RELAYHOST: ${MISP_POSTFIX_RELAY_HOST}
      RELAY_USER: ${MISP_POSTFIX_RELAY_USER}
      RELAY_PASSWORD: ${MISP_POSTFIX_RELAY_PASSWORD}
      DOCKER_NETWORK: ${DOCKER_NETWORK}
      DEBUG_PEER: ${MISP_POSTFIX_DEBUG_PEER}
      # MISP
      MISP_FQDN: ${MISP_FQDN}
      MISP_URL: ${MISP_URL}
      MISP_HTTPS_PORT: ${MISP_HTTPS_PORT}
      MISP_prefix: ${MISP_prefix}
      MISP_encoding: ${MISP_encoding}
      MISP_SALT: ${MISP_SALT}
      ADD_ANALYZE_COLUMN: ${MISP_ADD_ANALYZE_COLUMN}
      USE_PGP: ${MISP_USE_PGP}
      USE_SMIME: ${MISP_USE_SMIME}
      # Cron
      CRON_INTERVAL: ${MISP_CRON_INTERVAL}
      CRON_USER_ID: ${MISP_CRON_USER_ID}
      # PHP
      PHP_MEMORY_LIMIT: ${MISP_PHP_MEMORY_LIMIT}
      PHP_MAX_EXECUTION_TIME: ${MISP_PHP_MAX_EXECUTION_TIME}
      PHP_POST_MAX_SIZE: ${MISP_PHP_POST_MAX_SIZE}
      PHP_UPLOAD_MAX_FILESIZE: ${MISP_PHP_UPLOAD_MAX_FILESIZE}
    volumes:
    ###### mips-server ######
    # Apache2 Configuration
    - misp-vol-server-apache2-config-sites-enabled:/etc/apache2/sites-enabled
    # Volume with Certificates
    - misp-vol-ssl:/etc/apache2/ssl
    # Volume with PGP Key
    - misp-vol-pgp:/var/www/MISP/.gnupg
    # Volume with S/MIME Certificate and Key
    - misp-vol-smime:/var/www/MISP/.smime
    ###### misp-redis ######
    - misp-vol-redis-data:/redis_data_dir
    # MISP Configurations:
    - misp-vol-server-MISP-app-Config:/var/www/MISP/app/Config
    - misp-vol-server-MISP-cakeresque-config:/var/www/MISP/app/Plugin/CakeResque/Config
    - misp-vol-server-MISP-tmp:/var/www/MISP/app/tmp
    - misp-vol-server-MISP-attachments:/var/www/MISP/app/files
    ###### misp-db ######
    - misp-vol-db-data:/var/lib/mysql
    networks:
      misp-backend:
        aliases:
        - misp-server

  ### Reverse Proxy ###
  misp-proxy:
    # default-image-proxy=dockerhub.dcso.de/misp-dockerized-proxy:1
    image: ${MISP_IMAGE_PROXY}
    container_name: misp-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"    
    environment:
      MISP_FQDN: ${MISP_FQDN}
      HTTP_SERVERADMIN: ${MISP_HTTP_SERVERADMIN}
      IP: ${MISP_PROXY_IP}
      PHP_UPLOAD_MAX_FILESIZE: ${MISP_PHP_UPLOAD_MAX_FILESIZE}
      PHP_MAX_EXECUTION_TIME: ${MISP_PHP_MAX_EXECUTION_TIME}

      # ?HTTP_PROXY: ${MISP_PROXY_HTTP}
      # ?HTTPS_PROXY: ${MISP_PROXY_HTTPS}
      # ?NO_PROXY: ${MISP_PROXY_NO}
      http_proxy: ${MISP_PROXY_HTTP}
      https_proxy: ${MISP_PROXY_HTTPS}
      no_proxy: ${MISP_PROXY_NO}
    volumes:
      # NGINX Configuration
      #- misp-vol-proxy-conf:/etc/nginx/conf.d
      # SSL 
      - misp-vol-ssl:/etc/nginx/ssl
    networks:
      misp-backend:
        aliases:
          - misp-nginx


  ### Robot ###
  misp-robot:
    # default-image-robot=dockerhub.dcso.de/misp-dockerized-robot:2
    image: ${MISP_IMAGE_ROBOT}
    container_name: misp-robot
    restart: unless-stopped
    environment:
      MISP_FQDN: ${MISP_FQDN}
      http_proxy: ${MISP_PROXY_HTTP}
      https_proxy: ${MISP_PROXY_HTTPS}
      no_proxy: ${MISP_PROXY_NO}
    tty: true
    stdin_open: true
    healthcheck:
      disable: true
    volumes:
    # Github Repository
    - ${MISP_PROJECT_DIR}:/srv/MISP-dockerized
    ######  GLOBAL VOLUMES  ######
    # Docker.sock File
    - /var/run/docker.sock:/var/run/docker.sock:ro
    # Volume with Certificates
    - misp-vol-ssl:/srv/misp-ssl
    # Volume with PGP Key
    - misp-vol-pgp:/srv/misp-pgp
    # Volume with S/MIME Certificate and Key
    - misp-vol-smime:/srv/misp-smime
    ###### mips-server ######
    - misp-vol-server-apache2-config-sites-enabled:/srv/misp-server/apache2/sites-enabled
    - misp-vol-server-MISP-app-Config:/srv/misp-server/MISP/Config
    - misp-vol-server-MISP-cakeresque-config:/srv/misp-server/MISP/CakeResque/Config
    - misp-vol-server-MISP-tmp:/srv/misp-server/MISP/app/tmp
    - misp-vol-server-MISP-attachments:/srv/misp-server/MISP/app/files
    ###### misp-proxy ######
    - misp-vol-proxy-conf:/srv/misp-proxy/conf.d
    ###### misp-redis ######
    - misp-vol-redis-data:/srv/misp-redis
    ###### misp-db ######
    - misp-vol-db-data:/srv/misp-db
    networks:
      misp-backend:
        aliases:
          - misp-robot


### VOLUMES ###
volumes:
  misp-vol-ssl:
  misp-vol-pgp:
  misp-vol-smime:
  misp-vol-db-data:
  misp-vol-redis-data:
  misp-vol-server-apache2-config-sites-enabled:
  misp-vol-server-MISP-app-Config:
  misp-vol-server-MISP-cakeresque-config:
  misp-vol-server-MISP-tmp:
  misp-vol-server-MISP-attachments:
  misp-vol-proxy-conf:
