# Setup:
# tar xjf misp.tbz; rm misp/apache2-ssl/cert.pem
#

version: '3.1'

networks: 
  misp-backend:
    driver: bridge
    driver_opts:
     com.docker.network.bridge.name: "${BRIDGE_NAME}"
     com.docker.network.enable_ipv6: "false"
    ipam:
      config:
      - subnet: "${DOCKER_NETWORK}"

services:
  ### MISP Database ###
  # LINK: https://hub.docker.com/_/mariadb/
  misp-db:
    # default-image-db=mariadb:10.3.10-bionic
    image: ${MISP_IMAGE_DB}
    container_name: misp-db
    restart: unless-stopped
    environment:
      # DB
      MYSQL_ROOT_PASSWORD: ${MISP_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MISP_MYSQL_DATABASE}
      MYSQL_USER: ${MISP_MYSQL_USER}
      MYSQL_PASSWORD: ${MISP_MYSQL_PASSWORD}
    volumes:
    - ${VOLDIR}/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysql -u $$MYSQL_USER \"-p$$MYSQL_PASSWORD\" -h misp-db --execute 'show databases;'"]
      interval: 1m
      timeout: 15s
      retries: 5
    networks:
      misp-backend:
        aliases:
        - misp-db

  ### MISP Redis Server ###
  # LINK: https://docs.docker.com/samples/library/redis/
  # LINK: https://github.com/docker-library/docs/tree/master/redis
  misp-redis:
    # default-image-redis=dockerhub.dcso.de/misp-dockerized-redis:5-alpine3.9
    image: ${MISP_IMAGE_REDIS}
    restart: unless-stopped
    container_name: misp-redis
    command: ["redis-server", "--appendonly", "yes"] #For Data persistence
    healthcheck:
      test: ["CMD-SHELL", "[ $$(redis-cli ping) == PONG ] || exit 1"]
      interval: 1m30s
      timeout: 15s
      retries: 3
    volumes:
    - ${VOLDIR}/redis:/data
    networks:
      misp-backend:
        aliases:
        - misp-redis
  
  ### MISP Modules ###
  misp-modules:
    # default-image-modules=dockerhub.dcso.de/misp-dockerized-misp-modules:latest
    image: ${MISP_IMAGE_MODULES}
    container_name: misp-modules
    restart: unless-stopped
    environment:
      # REDIS
      REDIS_BACKEND: ${MISP_REDIS_FQDN}
      REDIS_PORT: ${MISP_REDIS_PORT}
      REDIS_PW: ${MISP_REDIS_PW}
      REDIS_DATABASE: ${MISP_REDIS_DATABASE}
      # PROXY
      http_proxy: ${MISP_PROXY_HTTP}
      https_proxy: ${MISP_PROXY_HTTPS}
      no_proxy:  ${MISP_PROXY_NO}
    networks:
      misp-backend:
        aliases:
          - misp-modules


  ### MISP Apache Server ###    
  misp-server:
    # default-image-server=dockerhub.dcso.de/misp-dockerized-server:2.4.117-debian
    image: ${MISP_IMAGE_SERVER}
    container_name: misp-server
    restart: unless-stopped
    environment:
      # DB
      MYSQL_HOST: ${MISP_MYSQL_HOST}
      MYSQL_PORT: ${MISP_MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: ${MISP_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MISP_MYSQL_DATABASE}
      MYSQL_USER: ${MISP_MYSQL_USER}
      MYSQL_PASSWORD: ${MISP_MYSQL_PASSWORD}
      # REDIS
      REDIS_FQDN: ${MISP_REDIS_FQDN}
      REDIS_PORT: ${MISP_REDIS_PORT}
      REDIS_PW: ${MISP_REDIS_PW}
      REDIS_DATABASE: ${MISP_REDIS_DATABASE}
      # PROXY
      http_proxy: ${MISP_PROXY_HTTP}
      https_proxy: ${MISP_PROXY_HTTPS}
      no_proxy:  ${MISP_PROXY_NO}
      # POSTFIX
      SENDER_ADDRESS: ${MISP_POSTFIX_SENDER_ADDRESS}
      DOMAIN: ${MISP_POSTFIX_DOMAIN}
      HTTP_SERVERADMIN: ${MISP_HTTP_SERVERADMIN}
      RELAYHOST: ${MISP_POSTFIX_RELAY_HOST}
      RELAY_USER: ${MISP_POSTFIX_RELAY_USER}
      RELAY_PASSWORD: ${MISP_POSTFIX_RELAY_PASSWORD}
      DOCKER_NETWORK: ${DOCKER_NETWORK}
      DEBUG_PEER: ${MISP_POSTFIX_DEBUG_PEER}
      # MISP
      MISP_FQDN: ${MISP_FQDN}
      MISP_URL: ${MISP_URL}
      MISP_HTTPS_PORT: ${MISP_HTTPS_PORT}
      MISP_prefix: ${MISP_prefix}
      MISP_encoding: ${MISP_encoding}
      MISP_SALT: ${MISP_SALT}
      ADD_ANALYZE_COLUMN: ${MISP_ADD_ANALYZE_COLUMN}
      PGP_ENABLE: ${MISP_USE_PGP}
      SMIME_ENABLE: ${MISP_USE_SMIME}
      HTTPS_ENABLE: ${MISP_USE_HTTPS}
      MISP_MODULES_URL: ${MISP_MODULES_URL}
      # Cron
      CRON_INTERVAL: ${MISP_CRON_INTERVAL}
      CRON_USER_ID: ${MISP_CRON_USER_ID}
      # PHP
      PHP_MEMORY_LIMIT: ${MISP_PHP_MEMORY_LIMIT}
      PHP_MAX_EXECUTION_TIME: ${MISP_PHP_MAX_EXECUTION_TIME}
      PHP_POST_MAX_SIZE: ${MISP_PHP_POST_MAX_SIZE}
      PHP_UPLOAD_MAX_FILESIZE: ${MISP_PHP_UPLOAD_MAX_FILESIZE}
    ports:
      - 8080:80
    networks:
      misp-backend:
        aliases:
        - misp-server
